# Backward-compatibility shim.
# All ORM models now live in app/models/ (split by domain).
# This file re-exports everything so existing imports continue to work.
from app.models import (  # noqa: F401
    Base,
    TimestampMixin,
    make_id,
    utc_now,
    OrganizationORM,
    UserORM,
    OrganizationSettingsORM,
    NotificationSettingsORM,
    IntegrationORM,
    CustomerORM,
    Ticket,
    TicketStatus,
    TicketPriority,
    TicketCategory,
    TicketORM,
    TicketMessageORM,
    TicketEventORM,
    TicketAssignmentORM,
    TagORM,
    TicketTagORM,
    KnowledgeSourceORM,
    KnowledgeDocumentORM,
    KnowledgeChunkORM,
    KnowledgeIngestionJobORM,
    AIRunORM,
    AIStepORM,
    AIToolCallORM,
    AISuggestedActionORM,
    AIResponseORM,
    AIToolDefinitionORM,
    ApiKeyORM,
    AuditLogORM,
    NotificationORM,
)
