/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tickets/$id': typeof TicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tickets/$id': typeof TicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tickets/$id': typeof TicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/knowledge-base'
    | '/settings'
    | '/tickets'
    | '/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/knowledge-base'
    | '/settings'
    | '/tickets'
    | '/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/knowledge-base'
    | '/settings'
    | '/tickets'
    | '/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  SettingsRoute: typeof SettingsRoute
  TicketsRoute: typeof TicketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
  }
}

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  SettingsRoute: SettingsRoute,
  TicketsRoute: TicketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
